apiVersion: v1
kind: Service
metadata:
  name: svc-sts-busybox
spec:
  selector:
    app: sts-busybox
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-busybox
spec:
  replicas: 1
  serviceName: svc-sts-busybox
  selector:
    matchLabels:
      app: sts-busybox
  template:
    metadata:
      labels:
        app: sts-busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do date +'%Y-%m-%d %H:%M:%S' >> /data/datafile; hostname >> /data/datafile; echo $HOSTNAME >> /data/datafile; sleep 2; done"]
        volumeMounts:
        - name: data
          mountPath: /data
            #      volumes:
            #      - name: data
            #        persistentVolumeClaim:
            #          claimName: busybox-pvc
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: powerstore-ext4
